apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  labels:
    app: citus-workers
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
