kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-worker
  labels:
    type: local

    app: citus-workers
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:

    path: "/home/workerdata"

    #path: "/home/azureuser/workerdata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-worker
  labels:

    app: citus-workers
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi