apiVersion: v1
kind: Service
metadata:
  name: citus-workers
  labels:
    app: citus-workers
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: citus-workers


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-workers
spec:
  serviceName: "citus-workers"
  replicas: 2
  selector:
    matchLabels:
      app: citus-workers
  template:
    metadata:
      labels:
        app: citus-workers
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - citus-workers
                    - citus-coordinator
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mobilitydb-cloud
        image: bouzouidja/mobilitydb-cloud:latest
        imagePullPolicy: "IfNotPresent"
        args:
            - -c
            - max_locks_per_transaction=128
            - -c
            - shared_preload_libraries=citus, postgis-3.so
            - -c
            - wal_level=logical
        ports:
        - containerPort: 5432
        #resources:
        #  limits:
        #    cpu: 500m
        #  requests:
        #    cpu: 200m

        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 9;printf \"local all all trust\nhost all all 127.0.0.1/32 trust\nhost all all ::1/128 trust\nhost all all 0.0.0.0/0 trust\nlocal replication all trust\nhost replication all 127.0.0.1/32 trust\nhost replication all ::1/128 trust \" > /var/lib/postgresql/data/pg_hba.conf;createdb -U $POSTGRES_USER  $POSTGRES_DB ;psql -U $POSTGRES_USER -d $POSTGRES_DB --command=\"SELECT pg_reload_conf();\"  ;psql -U $POSTGRES_USER -d $POSTGRES_DB --command=\" CREATE EXTENSION IF NOT EXISTS citus;\";psql -h citus-coordinator -U $POSTGRES_USER -d $POSTGRES_DB --command=\"SELECT * from citus_add_node('$POD_IP', 5432);\";"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "psql -h citus-coordinator -U $POSTGRES_USER -d $POSTGRES_DB --command=\"SELECT * FROM citus_set_node_property('$POD_IP', 5432, 'shouldhaveshards', false);\";psql -h citus-coordinator -U $POSTGRES_USER -d $POSTGRES_DB --command=\"SELECT citus_rebalance_start(drain_only := true);\"  ;psql -h citus-coordinator -U $POSTGRES_USER -d $POSTGRES_DB --command=\"SELECT * from citus_remove_node('$POD_IP', 5432);\";"]


        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m 
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB

        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim-worker